name : 'Php 8'

on:
  workflow_call:
  push:
    branches:
      - beta
    paths:
      - "**.php"
  pull_request:
    branches:
      - beta
      - master
    paths:
      - "**.php"

jobs:
  run-linters:
    name: Run On PHP 7.3
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: PHP syntax checker 8
        uses: prestashop/github-action-php-lint/7.3@v1
        with:
          folder-to-exclude: "! -path \"./3rdparty/*\" ! -path \"./vendor/*\""
